org: mirivera
app: asset-swap
service: asset-swap

provider:
    name: aws
    runtime: nodejs20.x
custom:
    bundle:
        linting: false
        externals:
            - knex
            - mysql

functions:
    refresh-orders:
        handler: src/handlers/refresh-order.refreshOrder
        timeout: 25
        memorySize: 10240
        events:
            - httpApi:
                  path: "/api/v1/load"
                  method: "POST"

    get-orders:
        handler: src/handlers/get-orders.getHttpOrders
        timeout: 25
        memorySize: 10240
        events:
            - httpApi:
                  path: "/api/v1/orders"
                  method: "GET"

    get-order:
        handler: src/handlers/get-orders.getHttpOrders
        timeout: 25
        memorySize: 10240
        events:
            - httpApi:
                  path: "/api/v1/orders/{orderId}"
                  method: "GET"

    chain-reader:
        handler: src/handlers/schedule/read-chain.chainReader
        timeout: 300
        memorySize: 10240
        events:
            - schedule:
                  name: chain-reader
                  rate: rate(1 minute)

plugins:
    - serverless-bundle
    - serverless-offline
