org: mirivera
app: asset-swap
service: asset-swap

provider:
    name: aws
    runtime: nodejs20.x
custom:
    bundle:
        linting: false

functions:
    refresh-orders:
        handler: src/handlers/refresh-order.refreshOrder
        timeout: 25
        memorySize: 1028
        events:
            - httpApi:
                  path: "/api/v1/load"
                  method: "POST"

    get-orders:
        handler: src/handlers/get-orders.getHttpOrders
        timeout: 25
        memorySize: 1028
        events:
            - httpApi:
                  path: "/api/v1/order"
                  method: "GET"

plugins:
    - serverless-bundle
    - serverless-offline
