org: mirivera
app: asset-swap
service: asset-swap

provider:
    name: aws
    runtime: nodejs20.x
custom:
    bundle:
        linting: false

functions:
    create-order:
        handler: src/handlers/create-order.createOrder
        timeout: 25
        memorySize: 1028
        events:
            - httpApi:
                  path: "/api/v1/create"
                  method: "POST"

plugins:
    - serverless-bundle
    - serverless-offline
